### ISSUE TITLE
Installation does not generate `lib`

### ISSUE THREAD

**Issue by trevorzablocki2** [socure-inc/socure-docv-wrapper-react-native#16]
Previously the project used a `bob build` command in the `prepare` script of the `package.json` to create the `lib` folder and build artifacts so they could be used but that was [removed in v2.1.0](https://github.com/socure-inc/socure-docv-wrapper-react-native/commit/381ae0396d76c978aea725891c065151ee1cc4a7). Are we supposed to run the build command ourselves post install now?

**Comment by buraksocure** [comment]
Hi @trevorzablocki2 Thanks for your comment. My understanding is, we used BOB in the beginning but we don't have to use anymore. I recommend you to test our latest V2s through our Sample App here  -> https://github.com/socure-inc/socure-docv-demo-app-react-native/tree/main/v2 and reach out to use through dse@socure.com if you have further questions. Thank you!
