### ISSUE TITLE
ERROR: Repository not found when doing pod install

### ISSUE THREAD

**Issue by neildevas** [socure-inc/socure-docv-wrapper-react-native#21]
I get the following error when doing a `pod install`:
```
🔥 [cocoapods-user-defined-build-types] patching build types...
Pre-downloading: `SocureSdk` from `git@github.com:socure-inc/socure-ios-sdk.git`

[!] Error installing SocureSdk
[!] Failed to download 'SocureSdk': [!] /usr/bin/git clone git@github.com:socure-inc/socure-ios-sdk.git /var/folders/sw/th_r94bd58q1yvww90kp5bq80000gn/T/d20230103-19457-2yycs5 --template= --single-branch --depth 1

Cloning into '/var/folders/sw/th_r94bd58q1yvww90kp5bq80000gn/T/d20230103-19457-2yycs5'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This is the line I added, as instructed in the Readme
`pod 'SocureSdk', :build_type => :dynamic_framework, :git => 'git@github.com:socure-inc/socure-ios-sdk.git'`. 

It works if I add the following: 
`pod 'SocureSdk', :build_type => :dynamic_framework, :git => 'git@github.com:socure-inc/socure-docv-sdk-ios.git'`

**Comment by buraksocure** [comment]
Hi @neildevas 

Thanks for reaching out. 

As you know, there is no PodFile in the RN Wrapper Repo. Pods needs to be defined on the React Native App Part which you can see on our Sample App -> https://github.com/socure-inc/socure-docv-demo-app-react-native/blob/main/v2/SampleApp/ios/Podfile#L12

and It's pointing to our latest iOS SDK V2 which is correct.

This repo is depreciated ->  socure-inc/socure-ios-sdk.git which means the change you made is correct. 

Feel free to reach out through dse@socure.com if you have any questions.
