### ISSUE TITLE
Main path in package.json

### ISSUE THREAD

**Issue by kajas90** [socure-inc/socure-docv-wrapper-react-native#22]
With current setup of `main` set to `lib/commonjs/index` jest with `react-native` setup fails to find the module, can I ask you to update main to point to `src/index`?

**Comment by buraksocure** [comment]
Hi @kajas90 Thanks for reaching out. I realized you were referring to this line -> https://github.com/socure-inc/socure-docv-wrapper-react-native/blob/main/package.json#L5

We will review this and get back to you but I strongly recommend you to use our DocV V3 SDK that we have an NPM package. 

NPM For V3 -> https://www.npmjs.com/package/@socure-inc/docv-react-native
Sample app for V3 -> https://github.com/socure-inc/socure-docv-demo-app-react-native

If you need further assistance please reach out to our Developer Support Engineering through dse@socure.com

Thank you

**Comment by kajas90** [comment]
we are using v3, couldn't find it on github :)

**Comment by kajas90** [comment]
It seems that you moved away from commonJS as bundler but the main still points into `lib/commonjs/index` @buraksocure
